apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
spec:
  selector:
    app: rtmp-server
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hls-service
spec:
  selector:
    app: rtmp-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
